package com.mycompany.examen2.views;

import com.mycompany.examen2.dao.FraseEncriptadaDAO;
import com.mycompany.examen2.model.FraseEncriptada;
import com.mycompany.examen2.util.ConexionSQLite;
import com.mycompany.examen2.util.Encriptador;
import java.nio.file.Files;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Inicio extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Inicio.class.getName());

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        setLocationRelativeTo(null); // Centra el JFrame en la pantalla

        // 1. LLAMAMOS A ConexionSQLite PARA ASEGURARNOS DE QUE LA TABLA EXISTA
        ConexionSQLite.crearTablas();

        // 2. Ahora sí, cargamos los datos en el JTable visual
        cargarTabla();
    }

    // Método para llenar el JTable con los datos de SQLite
    private void cargarTabla() {
        // Limpiamos la tabla primero
        DefaultTableModel modelo = (DefaultTableModel) jt_frases.getModel();
        modelo.setRowCount(0);

        // Obtenemos los datos de SQLite
        FraseEncriptadaDAO dao = new FraseEncriptadaDAO();
        java.util.List<com.mycompany.examen2.model.FraseEncriptada> lista = dao.obtenerFrases();

        // Llenamos la tabla fila por fila
        for (FraseEncriptada f : lista) {
            // Mostramos el texto encriptado y el tamaño del archivo de configuración (solo como referencia)
            modelo.addRow(new Object[]{
                f.getFrase(),
                "Config guardada (" + f.getConfig().length + " bytes)"
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtf_frase = new javax.swing.JTextField();
        jb_encriptar = new javax.swing.JButton();
        jb_desencriptar = new javax.swing.JButton();
        jb_limpiar = new javax.swing.JButton();
        jb_elimiar_registro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_frases = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Encriptador");

        jLabel2.setText("Frase");

        jb_encriptar.setText("Encriptar");
        jb_encriptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_encriptarMouseClicked(evt);
            }
        });

        jb_desencriptar.setText("Desencriptar");
        jb_desencriptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_desencriptarMouseClicked(evt);
            }
        });

        jb_limpiar.setText("Limpiar");
        jb_limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_limpiarMouseClicked(evt);
            }
        });

        jb_elimiar_registro.setText("Eliminar Registro");
        jb_elimiar_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_elimiar_registroMouseClicked(evt);
            }
        });

        jt_frases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Frase Encriptada", "Config"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt_frases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_frasesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_frases);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jtf_frase, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jb_encriptar)
                                .addGap(18, 18, 18)
                                .addComponent(jb_desencriptar)
                                .addGap(18, 18, 18)
                                .addComponent(jb_limpiar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jb_elimiar_registro)))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtf_frase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_encriptar)
                    .addComponent(jb_desencriptar)
                    .addComponent(jb_limpiar)
                    .addComponent(jb_elimiar_registro))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_encriptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_encriptarMouseClicked
        // 1. Obtener el texto ingresado y validar que no esté vacío
        String textoOriginal = jtf_frase.getText().trim();

        if (textoOriginal.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, ingresa una frase para encriptar.",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 2. Leer el archivo config.txt desde la raíz del proyecto
            java.io.File archivoConfig = new java.io.File("config.txt");

            if (!archivoConfig.exists()) {
                JOptionPane.showMessageDialog(this,
                        "No se encontró el archivo 'config.txt' en la raíz del proyecto.",
                        "Error de Archivo", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Convertimos el archivo a bytes (BLOB)
            byte[] configBytes = Files.readAllBytes(archivoConfig.toPath());

            // 3. Encriptar la frase usando nuestra clase cerebro
            String textoEncriptado = Encriptador.encriptar(textoOriginal, configBytes);

            // 4. Guardar en SQLite usando el Modelo y el DAO
            FraseEncriptada nuevaFrase = new FraseEncriptada();
            nuevaFrase.setFrase(textoEncriptado); // Guardamos el texto ya encriptado
            nuevaFrase.setConfig(configBytes);    // Guardamos la configuración exacta usada

            FraseEncriptadaDAO dao = new FraseEncriptadaDAO();

            if (dao.guardarFrase(nuevaFrase)) {
                // Mensaje de éxito
                JOptionPane.showMessageDialog(this,
                        "Frase encriptada y guardada con éxito:\n\nOriginal: " + textoOriginal + "\nEncriptada: " + textoEncriptado,
                        "Éxito", JOptionPane.INFORMATION_MESSAGE);

                // Limpiamos el campo de texto para una nueva entrada
                jtf_frase.setText("");

                // Llamada para actualizar la tabla visualmente (ver código extra abajo)
                cargarTabla();
            } else {
                JOptionPane.showMessageDialog(this,
                        "Ocurrió un error al guardar en la base de datos.",
                        "Error de BD", JOptionPane.ERROR_MESSAGE);
            }

        } catch (java.io.IOException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al leer el archivo de configuración: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Ocurrió un error inesperado: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jb_encriptarMouseClicked

    private void jb_desencriptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_desencriptarMouseClicked
        // 1. Verificar que el usuario haya seleccionado una fila en la tabla
        int filaSeleccionada = jt_frases.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, selecciona una frase de la tabla para desencriptar.",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 2. Obtener la lista de frases desde la base de datos
            FraseEncriptadaDAO dao = new FraseEncriptadaDAO();
            java.util.List<FraseEncriptada> lista = dao.obtenerFrases();

            // 3. Obtener el objeto correspondiente a la fila seleccionada
            // Como cargarTabla() y obtenerFrases() siguen el mismo orden, podemos usar el índice
            FraseEncriptada fraseSeleccionada = lista.get(filaSeleccionada);

            // 4. Desencriptar usando la clase cerebro (pasando la frase cifrada y SU propia configuración en bytes)
            String textoDesencriptado = Encriptador.desencriptar(
                    fraseSeleccionada.getFrase(),
                    fraseSeleccionada.getConfig()
            );

            // 5. Mostrar el resultado al usuario
            JOptionPane.showMessageDialog(this,
                    "Desencriptación Exitosa:\n\n"
                    + "Texto Encriptado: " + fraseSeleccionada.getFrase() + "\n"
                    + "Texto Original: " + textoDesencriptado,
                    "Resultado", JOptionPane.INFORMATION_MESSAGE);

            // Opcional: Colocar la frase original de vuelta en el campo de texto
            jtf_frase.setText(textoDesencriptado);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Ocurrió un error al desencriptar: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jb_desencriptarMouseClicked

    private void jb_limpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_limpiarMouseClicked
        // 1. Limpiar el campo de texto
        jtf_frase.setText("");

        // 2. Quitar la selección de cualquier fila en la tabla (por si había alguna seleccionada)
        jt_frases.clearSelection();

        // 3. Devolver el cursor al campo de texto para que puedas escribir inmediatamente
        jtf_frase.requestFocus();
    }//GEN-LAST:event_jb_limpiarMouseClicked

    private void jb_elimiar_registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_elimiar_registroMouseClicked
        // 1. Verificar que el usuario haya seleccionado una fila en la tabla
        int filaSeleccionada = jt_frases.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, selecciona un registro de la tabla para eliminar.",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Pedir confirmación al usuario antes de eliminar (Buena práctica)
        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Estás seguro de que deseas eliminar este registro de la base de datos?",
                "Confirmar Eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        // Si el usuario presiona "Sí" (YES_OPTION)
        if (confirmacion == JOptionPane.YES_OPTION) {
            try {
                // 3. Obtener la lista para saber qué objeto seleccionó
                FraseEncriptadaDAO dao = new FraseEncriptadaDAO();
                java.util.List<FraseEncriptada> lista = dao.obtenerFrases();

                // Obtenemos la frase usando el índice de la fila seleccionada
                FraseEncriptada fraseAEliminar = lista.get(filaSeleccionada);

                // 4. Llamamos al método eliminar del DAO
                if (dao.eliminarFrase(fraseAEliminar)) {
                    JOptionPane.showMessageDialog(this,
                            "Registro eliminado con éxito.",
                            "Éxito", JOptionPane.INFORMATION_MESSAGE);

                    // 5. Actualizamos la tabla para que desaparezca la fila borrada
                    cargarTabla();

                    // Limpiamos el campo de texto por si tenía algo escrito
                    jtf_frase.setText("");
                } else {
                    JOptionPane.showMessageDialog(this,
                            "No se pudo eliminar el registro en la base de datos.",
                            "Error de BD", JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this,
                        "Ocurrió un error al intentar eliminar: " + ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jb_elimiar_registroMouseClicked

    private void jt_frasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_frasesMouseClicked
        // 1. Obtener el índice de la fila a la que el usuario le hizo clic
        int filaSeleccionada = jt_frases.getSelectedRow();

        // 2. Verificar que la selección sea válida (no sea -1)
        if (filaSeleccionada != -1) {

            // 3. Obtener el valor de la columna 0 (que es donde está la "Frase Encriptada")
            // Usamos getValueAt(fila, columna)
            String textoSeleccionado = jt_frases.getValueAt(filaSeleccionada, 0).toString();

            // 4. Colocar ese texto en tu campo de texto jtf_frase
            jtf_frase.setText(textoSeleccionado);
        }
    }//GEN-LAST:event_jt_frasesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Inicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_desencriptar;
    private javax.swing.JButton jb_elimiar_registro;
    private javax.swing.JButton jb_encriptar;
    private javax.swing.JButton jb_limpiar;
    private javax.swing.JTable jt_frases;
    private javax.swing.JTextField jtf_frase;
    // End of variables declaration//GEN-END:variables
}
